#!/bin/sh

SINK_ICON=''
SINK_MUTED_ICON='ﳌ'
SOURCE_ICON=''
SOURCE_MUTED_ICON=''

if [ $# -ne 1 ] || { [ "$1" != "sink" ] && [ "$1" != "source" ]; } then
	echo "No command given. Try: sbaudio [sink|source]"
	exit 1
fi

DEVNAME="$1"
DEVICE="$(pactl get-default-$DEVNAME 2>/dev/null)"
if [ $? -ne 0 ]; then
	exit 2
fi

# Increase/decrease volume
if [ ! -z "$BLOCK_BUTTON" ]; then
	case $BLOCK_BUTTON in
		1) pactl set-$DEVNAME-mute $DEVICE toggle ; notify-send "Toggled $DEVNAME mute " ;;
                3) st -c wmprompt -e pulsemixer & notify-send "Started 'pulsemixer'  " ;;
		4) pactl set-$DEVNAME-volume $DEVICE +5% ; notify-send "Raised $DEVNAME volume by 5% ﱛ" ;;
		5) pactl set-$DEVNAME-volume $DEVICE -5% ; notify-send "Lowered $DEVNAME volume by 5% ﱜ" ;;
	esac
fi

VOL="$(pactl get-$DEVNAME-volume $DEVICE)"
VOL_LEFT="$(echo $VOL | cut -d ' ' -f 5 | head -n 1)"
VOL_RIGHT="$(echo $VOL | cut -d ' ' -f 12 | head -n 1)"
MUTED="$(pactl get-$DEVNAME-mute $DEVICE | cut -d ' ' -f 2)"

if [ "$DEVNAME" = "sink" ]; then
	if [ "$MUTED" = "yes" ]; then
		ICON=$SINK_MUTED_ICON
	else
		ICON=$SINK_ICON
	fi
else
	if [ "$MUTED" = "yes" ]; then
		ICON=$SOURCE_MUTED_ICON
	else
		ICON=$SOURCE_ICON
	fi
fi

if [ "$VOL_LEFT" = "$VOL_RIGHT" ]; then
	VOL="$VOL_LEFT"
else
	VOL="L:$SINK_VOL_LEFT R:$SINK_VOL_RIGHT"
fi

echo "${MOD_ICON_COLOR}$ICON ${MOD_TXT_COLOR}$VOL"

