#!/bin/sh

DATA_FILE="$HOME/.cache/sigma/battery"
BATTERY=""
if [ -f "$DATA_FILE" ]; then
	BATTERY="$(cat "$DATA_FILE")"
else
	BATTERY=$(ls /sys/class/power_supply/ | grep "^BAT" | head -1)
	if [ -z "$BATTERY" ]; then
		BATTERY="none"
	else
		echo "$BATTERY" > "$DATA_FILE"
	fi
fi

BATTERY_DIR="/sys/class/power_supply/$BATTERY"
if [ ! -d "$BATTERY_DIR" ]; then
	BAT_ICON="󱉞"
	echo "$BAT_ICON $BATTERY"
else
	BAT0_ICON=''
	BAT1_ICON=''
	BAT2_ICON=''
	BAT3_ICON=''
	BAT4_ICON=''
	CHARGING_ICON=''

	BATTERY_STATUS="$(cat ${BATTERY_DIR}/status)"
	BATTERY_CHARGE="$(cat ${BATTERY_DIR}/capacity)"

	if [ $BATTERY_CHARGE -le 10 ]; then
		BAT_ICON="$BAT0_ICON "
	elif [ $BATTERY_CHARGE -le 40 ]; then
		BAT_ICON="$BAT1_ICON "
	elif [ $BATTERY_CHARGE -le 60 ]; then
		BAT_ICON="$BAT2_ICON "
	elif [ $BATTERY_CHARGE -lt 100 ]; then
		BAT_ICON="$BAT3_ICON "
	else
		BAT_ICON="$BAT4_ICON "
	fi

	if [ "$BATTERY_STATUS" = "Charging" ]; then
		BAT_ICON="$BAT_ICON $CHARGING_ICON"
	fi

	echo "$BAT_ICON ${BATTERY_CHARGE}%"
fi

if [ "$BLOCK_BUTTON" = "1" ]; then
	if [ -z "$BATTERY_CHARGE" ]; then
		notify-send "󰅙  Battery Not Found: $BATTERY"
	else
		notify-send "$BAT_ICON Battery Charge ($BATTERY): ${BATTERY_CHARGE}%"
	fi
elif [ "$BLOCK_BUTTON" = "3" ]; then
	bat_list="$(ls /sys/class/power_supply/ | grep "^BAT")"
	dmenu_str=""
	for bat in $bat_list; do
		dmenu_str="$bat\n$dmenu_str"
	done
	bat="$(printf "$dmenu_str" | dmenu -p "Choose a battery")"
	if [ ! -z "$bat" ]; then
		echo "$bat" > "$DATA_FILE"
		notify-send "Battery Changed: $bat"
	fi
fi

