#!/bin/sh

mem_bytes="$(free | grep -E '^Mem:.*')"
total_bytes="$(echo $mem_bytes | cut -d " " -f 2)"
used_bytes="$(echo $mem_bytes | cut -d " " -f 3)"
usage_perc="$(expr $used_bytes \* 100 / $total_bytes)"

echo " Mem: ${usage_perc}%"

if [ "$BLOCK_BUTTON" = "1" ]; then
	mem="$(free -h | grep -E '^Mem:.*')"
	total="$(echo $mem | cut -d " " -f 2)"
	used="$(echo $mem | cut -d " " -f 3)"
	notif="$(echo "Used Memory  : ${used}\nTotal Memory  : ${total}")"
	notify-send "$notif"
fi
