#!/bin/sh

DATA_FILE="/tmp/nwusage.log"

last_rx=0
last_tx=0
new_rx=0
new_tx=0

convert_unit() {
	number="$(echo $1 | cut -d ' ' -f 1)"
	append_str="$2"
	if [ $number -ge 1024 ]; then
		number="$(expr $number / 1024) $append_str"
	else
		number="$1"
	fi

	echo "$number"
}

for iface in /sys/class/net/*; do
	iface_name="$(echo $iface | rev | cut -d '/' -f 1 | rev)"
	if [ $iface_name = "lo" ]; then
		continue
	fi
	iface_rx="$(cat ${iface}/statistics/rx_bytes)"
	iface_tx="$(cat ${iface}/statistics/tx_bytes)"
	new_rx=$(expr $new_rx + $iface_rx)
	new_tx=$(expr $new_tx + $iface_tx)
done

if [ -e "$DATA_FILE" ]; then
	last_rx="$(head -n 1 $DATA_FILE)"
	last_tx="$(tail -n 1 $DATA_FILE)"
else
	last_rx="$new_rx"
	last_tx="$new_tx"
fi

echo "${new_rx}\n${new_tx}" > $DATA_FILE

speed_rx="$(expr $new_rx - $last_rx) B/s"
speed_tx="$(expr $new_tx - $last_tx) B/s"

speed_rx="$(convert_unit "$speed_rx" 'KiB/s')"
speed_rx="$(convert_unit "$speed_rx" 'MiB/s')"
speed_rx="$(convert_unit "$speed_rx" 'GiB/s')"

speed_tx="$(convert_unit "$speed_tx" 'KiB/s')"
speed_tx="$(convert_unit "$speed_tx" 'MiB/s')"
speed_tx="$(convert_unit "$speed_tx" 'GiB/s')"

echo "   $speed_tx  $speed_rx"

if [ "$BLOCK_BUTTON" = "1" ]; then
	new_rx="$(convert_unit "$new_rx" "KiB")"
	new_rx="$(convert_unit "$new_rx" "MiB")"
	new_rx="$(convert_unit "$new_rx" "GiB")"

	new_tx="$(convert_unit "$new_tx" "KiB")"
	new_tx="$(convert_unit "$new_tx" "MiB")"
	new_tx="$(convert_unit "$new_tx" "GiB")"
        notif=$(echo "Total Downloads  : $new_rx\nTotal Uploads  :   $new_tx")
        notify-send "$notif"
fi
