#!/bin/sh

DATA_FILE="$HOME/.cache/sigma/nwif"

ETH_ICON_ON=''
ETH_ICON_OFF=''
WLAN_ICON_ON='直'
WLAN_ICON_OFF='睊'
UNPLUGGED_ICON="󰚦"

IFACE=""
ICON_ON=""
ICON_OFF=""
MATCH_STR="inet "

if [ -f "$DATA_FILE" ]; then
	IFACE="$(cat "$DATA_FILE")"
else
	IFACE="$(ls /sys/class/net | head -n 1)"
	if [ -z "$IFACE" ]; then
		IFACE="none"
	fi
	echo "$IFACE" > "$DATA_FILE"
fi

if [ ! -d "/sys/class/net/$IFACE" ]; then
	echo "$UNPLUGGED_ICON $IFACE"
	IFACE_STATE="unplugged"
	IPV4_ADDR="none"
	IPV6_ADDR="none"
else
	if [ -d "/sys/class/net/$IFACE/wireless" ]; then
		ICON_ON="$WLAN_ICON_ON"
		ICON_OFF="$WLAN_ICON_OFF"
	else
		ICON_ON="$ETH_ICON_ON"
		ICON_OFF="$ETH_ICON_OFF"
	fi

	IFACE_STATE="$(cat "/sys/class/net/$IFACE/operstate")"
	IPV4_ADDR="$(ip address show "$IFACE" | grep "inet " | head -n 1 | sed -E "s/\s+inet\s+//g" | cut -d " " -f 1)"
	IPV6_ADDR="$(ip address show "$IFACE" | grep "inet6 " | head -n 1 | sed -E "s/\s+inet6\s+//g" | cut -d " " -f 1)"
	if [ -z "$IPV4_ADDR" ]; then
		IPV4_ADDR="none"
	fi

	if [ -z "$IPV6_ADDR" ]; then
		IPV6_ADDR="none"
	fi

	if [ "$IFACE_STATE" = "up" ]; then
		echo "$ICON_ON $IFACE"
	else
		echo "$ICON_OFF $IFACE"
	fi
fi

if [ "$BLOCK_BUTTON" = "1" ]; then
	notif="$(printf "  Interface: $IFACE\n  State:     $IFACE_STATE\n󱄙  IPv4:      $IPV4_ADDR\n󱄙  IPv6:      $IPV6_ADDR")"
	notify-send "$notif"
elif [ "$BLOCK_BUTTON" = "3" ]; then
	iface_list="$(ls /sys/class/net/)"
	dmenu_str=""
	for iface in $iface_list; do
		dmenu_str="$iface\n$dmenu_str"
	done
	iface="$(printf "$dmenu_str" | dmenu -p "Choose an interface")"
	if [ ! -z "$iface" ]; then
		echo "$iface" > "$DATA_FILE"
                notify-send "  Interface Changed: $iface"
	fi
fi
