#!/bin/sh

printf " ⏻ \t\n"

if [ "$BLOCK_BUTTON" = "1" ]; then
	choice="$(printf "Lock Screen\nQuit\nPower Off\nReboot\n" | dmenu)"

	case "$choice" in
		"Lock Screen") slock ;;
		"Quit") pkill -9 dwm;;
		"Power Off") st -c "wmprompt" -f "$FONT" -- sudo poweroff;;
		"Reboot") st -c "wmprompt" -f "$FONT" -- sudo reboot;;
	esac
fi
