#!/bin/sh

printf "⏻ \t\n"

FONT="FiraCode Nerd Font:size=10"
DARKBLUE="#101a20"
NEONGREEN="#00ffc8"

alias dmenu='dmenu -fn "$FONT" -nb "$DARKBLUE" -nf "$NEONGREEN" -sb "$NEONGREEN" -sf "$DARKBLUE"'

if [ "$BLOCK_BUTTON" = "1" ]; then
	choice="$(printf "Lock Screen\nQuit\nPower Off\nReboot\n" | dmenu)"

	case "$choice" in
		"Lock Screen") slock ;;
		"Quit") pkill -9 dwm;;
		"Power Off") st -c "wmprompt" -f "$FONT" -- sudo poweroff;;
		"Reboot") st -c "wmprompt" -f "$FONT" -- sudo reboot;;
	esac
fi
