#!/bin/sh

# block openrc commands from 'setup-alpine'
# to prevent the X session from stopping
# by defining the env var MOCK used before
# some commands, including 'openrc' ones

if [ $# -gt 0 ] && [ $1 != "openrc" ]; then
	$@
fi
