#!/bin/sh

# setup filesystem
/bin/busybox mkdir -p usr/bin usr/sbin
/bin/busybox --install -s

modprobe -a loop squashfs sd-mod usb-storage overlay simpledrm
mount -t devtmpfs devtmpfs /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mdev -s
nlplug-findfs

mkdir -p /media/root-ro /media/root-rw/work /media/root-rw/root /media/cdrom
mount -t iso9660 /dev/sr0 /media/cdrom
mount -t squashfs /media/cdrom/profile.sfs /media/root-ro

mkdir -p sysroot/dev sysroot/proc sysroot/sys
mount -t overlay -o lowerdir=/media/root-ro,upperdir=/media/root-rw/root,workdir=/media/root-rw/work overlayfs sysroot
mount -t devtmpfs devtmpfs sysroot/dev
mount -t proc proc sysroot/proc # optional, openrc will mount the procfs it if it hasn't been mounted yet
mount -t sysfs sysfs sysroot/sys

# switch root
sh
exec /bin/busybox switch_root /sysroot /sbin/init
echo "initramfs emergency recovery shell launched"
exec /bin/busybox sh

