#!/bin/sh

# install busybox
/bin/busybox mkdir -p usr/bin usr/sbin
/bin/busybox --install -s

# setup filesystem
[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3
mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
mount -t devtmpfs -o exec,nosuid,mode=0755 devtmpfs /dev

[ -c /dev/kmsg ] || mknod -m 660 /dev/kmsg c 1 11
mount -t proc -o noexec,nosuid,nodev proc /proc

[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || mkdir -m 755 /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

[ -d /dev/shm ] || mkdir /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

# setup devices
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s
nlplug-findfs

# setup modules
modprobe -a loop squashfs sd-mod usb-storage overlay simpledrm

# debug shell
sh

# mount devices
## fix for usb:
## losetup -r -f /dev/sdX # replace X with the drive letter
## mount -t iso9660 /dev/loop0 /media/cdrom/

## find sigma-linux device
BOOTDEV="$(blkid | grep -E '(.*):.*\s*LABEL="sigma-linux".*\s*TYPE="iso9660".*$' | head -n 1 | cut -d ':' -f 1)"
if [ -z "$BOOTDEV" ]; then
    echo "Unable to find boot device"
fi

mkdir -p /media/root-ro /media/root-rw/work /media/root-rw/root /media/cdrom
mount -t iso9660 "$BOOTDEV" /media/cdrom
mount -t squashfs /media/cdrom/profile.sfs /media/root-ro

# mount overlay and setup new root
mkdir -p sysroot/dev sysroot/proc sysroot/sys
mount -t overlay -o lowerdir=/media/root-ro,upperdir=/media/root-rw/root,workdir=/media/root-rw/work overlayfs sysroot
mount -t devtmpfs devtmpfs sysroot/dev
mount -t proc proc sysroot/proc # optional, openrc will mount the procfs it if it hasn't been mounted yet
mount -t sysfs sysfs sysroot/sys

# clear root password
chroot /sysroot passwd -d root

# switch root
exec /bin/busybox switch_root /sysroot /sbin/init
echo "initramfs emergency recovery shell launched"
exec /bin/busybox sh

