#!/bin/sh

# BSPWM settings

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config normal_border_color '#142414'
bspc config focused_border_color '#00FFC8'

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start programs
xsetroot -cursor_name left_ptr

feh --bg-fill /usr/share/backgrounds/wallpaper.png

pkill -9 sxhkd
sxhkd &

sh ~/.config/polybar/launch.sh &

sh ~/.config/picom/launch.sh &

pkill -9 pipewire
/usr/libexec/pipewire-launcher &
