.Dd March 15, 2021
.Dt SVKBD 1
.Os
.Sh NAME
.Nm svkbd
.Nd simple virtual keyboard
.Sh SYNOPSIS
.Nm
.Op Fl D
.Op Fl d
.Op Fl g Ar geometry
.Op Fl fn Ar font
.Op Fl O
.Op Fl h
.Op Fl H Ar heightfactor
.Op Fl l Ar layers
.Op Fl s Ar layer
.Op Fl v
.Sh DESCRIPTION
.Nm
is a simple virtual keyboard for X.org, intended to be used in environments, where no
keyboard is available.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl D
Debug mode; output verbosely to stderr.
.It Fl d
Set the _NET_WM_WINDOW_TYPE_DOCK property to hint windowmanagers it is
dockable, by default off.
.It Fl fn Ar font
Defines the font or font set used. e.g. "Monospace:bold:size=20" (an Xft font).
.It Fl g Ar geometry
Adjust the initial window position or size as specified by the standard X11
geometry format.
.It Fl h
Show the usage information.
.It Fl H Ar heightfactor
Affects the vertical space taken by the keyboard.
One row of keys takes up 1/heighfactor of the screen's total height.
.It Fl l Ar layers
Comma separated list of layers to enable (by name). If not set, all layers
in the layout will be available.
The layer names are defined by the layout you compiled.
.It Fl n
Do not simulate key presses for X
.It Fl R
Disable press-on-release
.It Fl s Ar layer
The layer to show on program start-up (by name). If not set, the first
layer of the layout will be shown.
.It Fl O
Disable overlay functionality.
.It Fl o
Print pressed keys to standard output
.It Fl v
Show the version information.
.El
.Sh ENVIRONMENT
The following environment variables can be defined, providing
an alternative to some of the command line parameters.
The command line parameters, however, always take precedence:
.Bl -tag -width Ds
.It Ev SVKBD_LAYERS
Comma separated list of layers to enable (by name). The layer names are defined by the layout
you compiled.
.It Ev SVKBD_ENABLEOVERLAYS
Set this to 0 if you want to disable overlay functionality.
.It Ev SVKBD_HEIGHTFACTOR
Affects the vertical space taken by the keyboard.
One row of keys takes up 1/heighfactor of the screen's total height.
.El
.Sh XRESOURCES
The appearance of svkbd can be configured via xresources:
.Bl -tag -width Ds
.It Ev svkbd.font
An Xft font specification like "Monospace:bold:size=20".
.It Ev svkbd.background
The background colour for the keycaps (in #rrggbb syntax)
.It Ev svkbd.foreground
The foreground colour for the keycaps (in #rrggbb syntax)
.It Ev svkbd.shiftforeground
The foreground colour for the secondary labels (shift layer) on the keycaps
.It Ev svkbd.shiftbackground
The background colour for the secondary labels (shift layer) on the keycaps
.It Ev svkbd.abcforeground
.It Ev svkbd.abcbackbround
The colour for alphabetical keys
.It Ev svkbd.abcshiftbackground
.It Ev svkbd.abcshiftforeground
The colour for the secondary labels (shift layer) on alphabetical keys
.It Ev svkbd.pressforeground
.It Ev svkbd.pressforebackground
The colour for keys when held pressed
.It Ev svkbd.highlightforeground
.It Ev svkbd.highlightforebackground
The colour for keys when hovering over them or just after release
.It Ev svkbd.highlightshiftforeground
.It Ev svkbd.highlightshiftforebackground
The colour for the secondary label on keys when hovering over them or just
after release
.It Ev svkbd.overlayforeground
.It Ev svkbd.overlaybackground
The colour for keys when they are part of an overlay
.It Ev svkbd.overlayshiftforeground
.It Ev svkbd.overlayshiftbackground
The colour for the secondary label on keys when they are part of an overlay
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr XParseGeometry 3
.Sh AUTHORS
.An Christoph Lohmann Aq Mt 20h@r-36.net
.An Enno Boland Aq Mt gottox@s01.de
.An Miles Alan Aq Mt m@milesalan.com
.An Maarten van Gompel Aq Mt proycon@anaproy.nl
.An Tetrakist Aq Mt tetrakist@mutandum.com
.An Stacy Aq Mt stacy@stacyharper.net
