.\" Manual page for Sigma Linux
.\" Author: Rdbo
.TH sigma-linux 1 "07 February 2023" "sigma-linux man page"

.SH NAME
sigma-linux

.SH DESCRIPTION
Sigma Linux operating system manual

.SH INSTALLATION
.B OBS: The 'Super' key is also known as 'Windows key'

To install Sigma Linux, open a terminal by pressing the keys
.B Super + Shift + Enter
.P
Then, run the command
.B setup-sigma
and follow the installation steps

.SH SHORTCUTS
.IP
.B TAB SHORTCUTS
.IP
Super + {1..9} -> Switch tab

Super + 0 -> Select all tabs

Super + Ctrl + {1..9} -> Select another tab

Super + B -> Hide status bar

.IP
.B WINDOW SHORTCUTS
.IP
Super + {J,K} -> Change window focus

Super + {H,L} -> Change selected window size

Super + T -> Switch to tiling mode

Super + F -> Switch to floating mode

Super + M -> Switch to monocle mode

Super + Shift + F -> Toggle fullscreen mode

Super + Left Mouse Click -> Move window

Super + Right Mouse Click -> Resize window

Super + Shift + C -> Close selected window

Super + Shift + {0..9} -> Move selected window to tab

Super + Enter -> Set selected window as master

Super + Shift + K -> Raise window on stack

Super + Shift + J -> Lower window on stack

Super + I -> Increase number of masters

Super + D -> Decrease number of masters

.IP
.B APPLICATION SHORTCUTS
.IP

Super + Shift + Enter -> Open terminal

Super + Shift + M -> Show manual

Super + Shift + B -> Open Web Browser

Super + Shift + Esc -> Change Keyboard Layout

.IP
.B SESSION SHORTCUTS
.IP
Super + Shift + Q -> Quit session

Super + Shift + X -> Lock session (type user password and press enter to unlock)
