.\" Manual page for Sigma Linux
.\" Author: Rdbo
.TH sigma-linux 1 "15 October 2022" "sigma-linux man page"

.SH NAME
sigma-linux

.SH DESCRIPTION
Sigma Linux configuration for Debian

.SH SHORTCUTS
.IP
.B TAB SHORTCUTS
.IP
Win + {1..9} -> Switch tab

Win + 0 -> Select all tabs

Win + Ctrl + {1..9} -> Select another tab

Win + B -> Hide status bar

.IP
.B WINDOW SHORTCUTS
.IP
Win + {J,K} -> Change window focus

Win + {H,L} -> Change selected window size

Win + T -> Switch to tiling mode

Win + F -> Switch to floating mode

Win + M -> Switch to monocle mode

Win + Shift + F -> Toggle fullscreen mode

Win + Left Mouse Click -> Move window

Win + Right Mouse Click -> Resize window

Win + Shift + C -> Close selected window

Win + Shift + {0..9} -> Move selected window to tab

Win + Enter -> Set selected window as master

Win + Shift + K -> Raise window on stack

Win + Shift + J -> Lower window on stack

Win + I -> Increase number of masters

Win + D -> Decrease number of masters

.IP
.B APPLICATION SHORTCUTS
.IP

Win + Shift + Enter -> Open terminal

Win + Shift + M -> Show manual

.IP
.B SESSION SHORTCUTS
.IP
Win + Shift + Q -> Quit session

Win + Shift + X -> Lock session (type user password and press enter to unlock)
