#!/bin/sh

set -e

# Helpers
separator() {
	echo
	echo "--------------------------------"
	echo
}

list_timezones() {
	echo "$(cd /usr/share/zoneinfo && find * -type f | grep -v "\." | grep -E '^[A-Z]')"
}

list_disks() {
	local disks="$(lsblk -p | grep -E 'disk\s+$' | cut -d ' ' -f 1)"

	# Make sure that the disk device actually exists
	for disk in $disks; do
		if [ -b "$disk" ]; then
			echo "$disk"
		fi
	done
}

# Setup
echo "Sigma Linux Installer"
echo "Welcome to the Sigma Linux Installer"
echo "Follow the instructions to proceed with your installation"

separator

# Select disk to install OS
echo "[*] DISK SETUP"
echo

# TODO: Check if disk size is enough
disks="$(list_disks)"
disk=""
while [ -z "$disk" ]; do
	echo "Available disks:"
	list_disks | tr '\n' ' '
	echo
	echo

	read -p "[p] Select a disk for installation: " disk
	if ! echo "$disks" | tr ' ' '\n' | grep -E "^$disk\$" > /dev/null; then
		echo "[!] Invalid disk! Select another one."
		usleep 500000
		echo
		disk=""
	fi
done

echo
echo "WARN: The disk '$disk' will be erased and the OS will be installed!"
read -p "[p] Type 'YES' to continue (without quotes): " response
if [ "$response" != "YES" ]; then
	echo "Installation cancelled"
	exit 0
fi

echo

echo "Setting up partition table..."
echo "label: gpt" | sfdisk -f "$disk"
echo ", 512M, uefi" | sfdisk -f "$disk" # EFI
echo ", 1G, linux" | sfdisk -a -f "$disk" # Boot
echo ", , linux" | sfdisk -a -f "$disk" # RootFS

echo "Formating partitions..."
yes | mkfs.vfat "$disk"1
yes | mkfs.ext2 "$disk"2
yes | mkfs.ext4 "$disk"3

echo "Mounting new root filesystem..."
newroot="$(mktemp -d)"
mount "$disk"3 "$newroot"
mkdir -p "$newroot/boot"
mount "$disk"2 "$newroot/boot"
mkdir -p "$newroot/boot/efi"
mount "$disk"1 "$newroot/boot/efi"
echo "Mounted root filesystem at: $newroot"

echo "Copying files..."
cp -r /squash/. "$newroot/"

echo "Mounting pseudo filesystems on new root..."
mkdir -p "$newroot/dev" "$newroot/proc"
mount -t devtmpfs none "$newroot/dev"
mount -t proc proc "$newroot/proc"

echo "Setting up boot..."
chroot "$newroot" grub-install --target=x86_64-efi --boot-directory=/boot --efi-directory=/boot/efi --removable "$disk"
cp /cdrom/boot/grub/grub.cfg /cdrom/boot/grub/wallpaper.png "$newroot/boot/grub/"
# Patch GRUB config
sed -i -E 's|/boot||g' "$newroot/boot/grub/grub.cfg"
sed -i -E 's|linux /vmlinuz |linux /vmlinuz sigmaroot="LABEL=hello" |' "$newroot/boot/grub/grub.cfg"
cp /cdrom/boot/vmlinuz /cdrom/boot/config /cdrom/boot/initramfs "$newroot/boot/"

echo "Unmounting partitions..."
umount "$newroot/proc"
umount "$newroot/dev"
umount "$newroot/boot/efi"
umount "$newroot/boot"
umount "$newroot"

echo "Cleaning up..."
rm -rf "$newroot"

echo "Syncing disks..."
sync

echo "Sigma Linux installed successfully!"
