#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Try again. Usage: mybattery [BATTERY]"
	exit 1
fi

BATTERY_DIR="/sys/class/power_supply/$1"
if [ ! -d $BATTERY_DIR ]; then
	echo "Invalid battery"
	exit 2
fi

BAT0_ICON=''
BAT1_ICON=''
BAT2_ICON=''
BAT3_ICON=''
BAT4_ICON=''
CHARGING_ICON=''

BATTERY_STATUS="$(cat ${BATTERY_DIR}/status)"
BATTERY_CHARGE="$(cat ${BATTERY_DIR}/capacity)"

if [ $BATTERY_CHARGE -le 10 ]; then
	BAT_ICON="%{F#ff6464}$BAT0_ICON "
elif [ $BATTERY_CHARGE -le 25 ]; then
	BAT_ICON="%{F#ff6464}$BAT1_ICON "
elif [ $BATTERY_CHARGE -le 50 ]; then
	BAT_ICON="%{F#ffff64}$BAT2_ICON "
elif [ $BATTERY_CHARGE -lt 100 ]; then
	BAT_ICON="%{F#64ff64}$BAT3_ICON "
else
	BAT_ICON="%{F#64ff64}$BAT4_ICON "
fi

if [ "$BATTERY_STATUS" = "Charging" ]; then
	BAT_ICON="$BAT_ICON $CHARGING_ICON"
fi

echo "$BAT_ICON %{F#ffffff}${BATTERY_CHARGE}%"
