name: Build ISO

on: [workflow_dispatch]

jobs:
    container-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Container build step
              uses: ./
              id: container
