name: Build ISO

on: [workflow_dispatch]

jobs:
    container-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Container Build Step
              uses: ./
              id: container
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: sigma-linux
                path: ${{ github.workspace }}/cache/sigma-linux.iso
                compression-level: 0
